### ISSUE TITLE
Binding to Internal Collection

### ISSUE THREAD

**Issue by genaropicazo** [Laboratory/Meteor-Custom-Audit#1]
Hi, it would be really nice if the internal collection was exposed. Currently, I am binding to it by doing:

```
<code>return Audit._collection.find({}, {sort: {created_at: -1}});</code>
```

but might feel more natural if there was a way to do it like:

```
<code>return AuditLogs.find({}, {sort: {created_at: -1}});</code>
```

This is working fine and updates when a new item is added or removed from the collection. However, when a document is modified, the collection is not updated -- not sure if this is on purpose so audit records cannot be modified -- I'll be looking into the source shortly. In my case, modifying makes sense since I am using it to track user activity where some actions can be undone (flagged as undone instead of deleting them).

**Comment by genaropicazo** [comment]
Non-Issue... problem was on my end.

**Comment by Laboratory** [comment]
@genaropicazo u can try to use loggin system https://github.com/superstringsoftware/observatory in test mode, we will soon release official beta testing

**Comment by genaropicazo** [comment]
@Laboratory Thank you, but I ended up writing my own package, which serves my needs for now.
